### ISSUE TITLE
Establishing template

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#1]
- Update the `titleStmt` and `<publicationStmt>` : copy from the inscription template one. 
Does it need to be change for Andrea's previous publication, as well as Marine and Aditia mentioning their PhD rather than the project?

- Add the `<listWit>`: Talk with @alevivier about the model used and how to align it as much as possible with the Epigraphy  ontology in order to produce the rdf files. So far 2 propositions are in shown in the template. What about the depth of information?

- Processing instruction set on tei-all validation schema: to be changes as for a "_current_" Dharma one, declare with **`https://raw.githubusercontent.com/erc-dharma/project-documentation/master/schema`**

- bibliography: I have kept the `<div type="bibliography">` : discuss the need here.

**Comment by arlogriffiths** [comment]
Please take a look at [](https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/Svayambhu-CritEd.xml) and see whether any of its teiHeader elements can be taken over in the template.

**Comment by ajaniak** [comment]
- Regarding `<editor ref="https://viaf.org/viaf/11026260/">`: why not simply used the ID system set for the project to point towards all the authorities rather than just one? 
- About the `<witness>`, TEI guidelines recommend that manuscripts defined in the list of witnesses be supplied with a pointer to a complete description of the manuscript elsewhere. We can use either `<msDesc>` element directly in the file or plan for an external resource.
- Maybe we could plan for a better link than the google doc one for the `<tagsDecl>`.
- Maybe allowing a possibility to use `<editorialDecl>` to provide details of editorial principles. Probably useful for Aditia and Marine.
- Plan to add a reference declaration `<refsDecl>`to describe the reference system used in the text. 
- Adding a `<textClass>`for keywords


Since we would be adding a `<projectDesc>`, we could move the `<note>`: "This project has received funding from the European Research..." inside `<projectDesc>`, it hasn't been done initially for the Inscription template since we wanted a really reduced header.

I will plan a newer template for manuscripts depending your feedbacks based on Svayambhu-CritEd.xml

**Comment by arlogriffiths** [comment]
- understood: I have removed the viaf and used the project id
- what would be the respective advantage of either approach? we will have only a small number of cases where a single witness is cited in more than one edition, so I am inclined to suggest that we set up the template so that we work with msDesc — but I need your advice on potential advantages of the other approach (and if we use the other, whether we should have a single authority file only for tfd-nusantara, or for all work in tfd)
- yes, the google doc link was just provisional, until we have a guide formally released: please set the template up in the way that seems best to you
- yes, please set up the template to include `<editorialDesc>` (I have never used this but it sounds useful)
- alright, please set up the template with `<refsDecl>` (I have never used this)
- alright, add `<textClass>` too

For all of these things, please draft a paragraph describing their usage in the google doc for our critical editions encoding guide.

**Comment by ajaniak** [comment]
- ok, great. 
- The pointer system is related to the way the manuscripts module was built in TEI through projects focus on the cataloguing. It can be useful to have when an edition gathers a lot of witnesses or if you want lot of details and indeed allows citation in several files when necessary. It simplifies the "reusability". A slight <msDesc> should be enough for now. If necessary at a latter stage, I will be able to move them. 
- I will move that up in my priority list and add the following points to the guidelines.

**Comment by arlogriffiths** [comment]
@ajaniak : is there anything still relevant in this issue?

**Comment by ajaniak** [comment]
I have checked and no. So I am closing this issue
