### ISSUE TITLE
Display: interpretation of smart quote

### ISSUE THREAD

**Issue by m-schoettel** [erc-dharma/tfd-nusantara-philology#10]
In the titles of the div type="chapter", the smart quotes are not interpreted as "curly" quotation marks.

Example:
<head type="editorial">The four perfections (<foreign>caturpāramitā</foreign>) of the hermits and the pursuit of the realm's prosperity</head>

display:

<img width="660" alt="Screenshot 2021-02-15 at 11 30 41" src="https://user-images.githubusercontent.com/26002486/107935592-e0540880-6f81-11eb-9a8a-0bebf8e0d613.png">

 @ajaniak: can we fix this?

**Comment by m-schoettel** [comment]
@arlogriffiths

**Comment by ajaniak** [comment]
I can implement it, but i need more precision regarding the context. 
Is it to be done for : 
- every quotation mark 
- only for the `<head type="editiorial">` element
- all the editorial part so also the notes in the apparatus

I can't really based myself on the @xml:lang='eng' and since the structure is less fragmented than the inscriptions XML structures, I need more informations regarding your expect before answering your request. And also a list to what you would expect regarding editorial changes could be great to build a solution for all and not added pieces of codes for each case.

For now, I have added a mapping character feature so `'` becomes what you expect, but note it is done in batch without regards for context, so you might find dirty part such as `’to be together’`

**Comment by m-schoettel** [comment]
Thanks a lot! 

It is to be done everywhere, that is:
- in all `<head type="editorial">` elements
- in the edited text per se (mainly in the Sanskrit stanzas)
- in the notes in the apparatus

However, for the latter, segments between single inverted commas such as `’to be together’` would have to be displayed with two different characters for the opening and closing marks. Would it be useful to encode them in a particular way to implement the changes automatically?

I will prepare a list of editorial changes in a separate issue.

**Comment by ajaniak** [comment]
The previous code should work fine then. 

I would go for a simple element `<q>` for the part such as `’to be together’`

**Comment by arlogriffiths** [comment]
I agree. Always use <q> where relevant. Encoding as well as display should be identical between epigraphic and manuscript based editions on all points relating to quotation marks and apostrophes.
________________________________

**Comment by arlogriffiths** [comment]
@m-schoettel @aditiagunawan : please confirm you have taken note of the rule that you should use `<q>abc</q>` if you want to get ‘abc’ in display. once you have confirmed, this issue can be closed.

**Comment by m-schoettel** [comment]
I have taken note of that rule.

**Comment by aditiagunawan** [comment]
Ok. Noted. Thanks.

**Comment by arlogriffiths** [comment]
thanks Marine en Aditia!
