### ISSUE TITLE
Issues regarding the pdf output

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#100]
Identified issues
- [x] lac. for larger gap sometimes displayed when not supposed to. (issue is with the Xpath using preceding-sibling. )
- [x] resolving the issue regarding the display of siglum with lac.
- [x] num in lemma not displayed
- [x] `@rend` hyphen and circle for lem or rdg
- [x] omission for larger gap need to be added
- [x] `@cause` on rdg
- [x] change the lemma separator
- [x] aligning subscript and superscript
- [x] Final dot punctuation in app:
    - [x] missing after om. and before a note
    - [x] missing after lac.
    - [x] final dot present between lemma separator and note, when no variant
    - [x] irregular spaces in the app entries
- [x] adding conditions to display all the possibilities of ptr
- [x] issue with some square brackets in translations
- [x] issue regarding parellels have been identified: impossible to gather at the bottom of the page several parallels in same case, so moved on the following page. 
- [x] ledrightnote should be deleted
- [x] pb overflow of some words => have shown Aditia how to fill the hyphenation section

Questions
- [x] `<gap reason="lost" quantity="1" unit="character"/><gap reason="lost" quantity="1" unit="component"/>`currently in the latex as `[1+][1+]` but in DHARMA, `[1+][.]`, should I align both and if yes, on which solution?

**Comment by arlogriffiths** [comment]
thanks! 

- are you able to look into and perhaps solve the issues you have identified?
- not sure what you mean with "keep it under" but yes, @cause should be processed by xslt and the display should be exactly as in html
- for all issues of display of editorial tagging in `<rdg>`, let us try to maximally align with display of diplomatic editions

**Comment by aditiagunawan** [comment]
@ajaniak 
Thank you. 
- The problem of Lac for larger gap is probably due to my unfinished encoding of `<lacunaStart>` and `<lacunaEnd>` of Sasana Mahaguru (if the problem found in this file). I will fix this problem as soon as possible.

- `@cause` in `<rdg>` is very important, please proceed as we have in html.
 
- I also notice in the apparatus that there is a space before the punctuation marks (dot and comma) to separate witness and the other lemma.

<img width="747" alt="Screenshot 2022-12-17 at 08 49 04" src="https://user-images.githubusercontent.com/55530631/208217651-4c65468e-91a7-4d73-b4be-8487b7136cb5.png">

Thank you.

**Comment by arlogriffiths** [comment]
@ajaniak 
- please try to eliminate those spaces before punctuation signs pointed out by Aditia (it's found also before semi-colon, as his screenshot shows)
- I am not satisfied with the lemma sign we currently use, and wish to revert to bold **]** as we use in html: can you implement this?

**Comment by ajaniak** [comment]
<img width="763" alt="Capture d’écran 2022-12-19 à 10 59 28" src="https://user-images.githubusercontent.com/33328906/208399524-bc322cef-7634-4dee-acbb-7314624352e6.png">
the separator has been updated and the `@cause` added. I don't known the code well enough yet to deal with all the spaces issues, but I am working on it.

**Comment by aditiagunawan** [comment]
Dear @ajaniak 

I would like to add an attribute which is missing in the pdf, that is a `@hyphen`(I use hyphenright and hyphenleft) in the lemma.

Best,

**Comment by ajaniak** [comment]
dear @aditiagunawan, 

I have just pushed a code for it; see pinaka 
<img width="756" alt="Capture d’écran 2022-12-19 à 12 00 10" src="https://user-images.githubusercontent.com/33328906/208411356-4b4873f8-aecd-4c36-ab91-5b53b6a72e10.png">

**Comment by aditiagunawan** [comment]
Dear @arlogriffiths 

There is no problem in my pdf file regarding your screenshot. Probably this is an unicode issue.

<img width="291" alt="Screenshot 2022-12-19 at 18 36 41" src="https://user-images.githubusercontent.com/55530631/208417729-905ec77e-22d9-4571-b584-7a00276a06fa.png">

**Comment by aditiagunawan** [comment]
Dear @aso2101 

Parallel issues have not been resolved. See screenshot of my Sasana Mahaguru file. The problem is that the line numbering in apparatus doesn't refer to the correct line number in the main text. I would expect the number to be 4–9 instead of 2–3.


<img width="733" alt="Screenshot 2023-01-17 at 06 01 21" src="https://user-images.githubusercontent.com/55530631/212778251-cf200948-7f5d-492d-9d00-7d2b3f2a02bb.png">

And this is the encoding:
<img width="1318" alt="Screenshot 2023-01-17 at 06 12 26" src="https://user-images.githubusercontent.com/55530631/212778512-15ad6492-80f6-484e-9e1c-33ad86146bbd.png">

Aditia

**Comment by aso2101** [comment]
Did you or Axelle generate that file? Here is how LaTeX produces it on my side, with the generated LaTeX code below. If you still get the same update after using the new stylesheet (in the `parallels` branch of the repository), kindly paste the LaTeX code (from `99-sasana-generated.tex`) and I will see what the problem seems to be.

![image](https://user-images.githubusercontent.com/997807/214211781-f31ab291-a2e7-4542-aced-5ff1d84f675a.png)
`\pstart
\label{p:sasanamahaguru_08.03}\edlabel{parallel-d1e2450-start}\maintextlang{ka, \edtext{\textbf{akrodho}}{\lemma{\textbf{akrodho}}\variant{\emph{norm.}; \maintextlang{Akva2dva\ } \textbf{\textsc{A}}.}} ṅaranya, tan dadi ikaṅ saṅ sevaka darma, mitonakən \edtext{krodanya riṅ}{\lemma{krodanya riṅ}\variant{\emph{em.}; \maintextlang{kva2danyaniṁ\ } \textbf{\textsc{A}}.}} harəpən saṅ matuha, maṅkaṅuni di nu reya, \edtext{\textbf{āhāralāghavam}}{\lemma{\textbf{āhāralāghavam}}\variant{\emph{em.}; \maintextlang{Aralagavəg·\ } \textbf{\textsc{A}}.}} ṅaranya, teka sumari sumarəmbah, hantə ṅənah basa ñatu basa ṅinum, di harəpən saṅ pandita, \edtext{\textbf{apramādaś ca pañca vaite}}{\lemma{\textbf{apramādaś ca pañca vaite}}\variant{\emph{conj.}; \maintextlang{Ahanaprəmadasvate\ } \textbf{\textsc{A}}.}} \edtext{ṅaranya}{\lemma{ṅaranya}\variant{\emph{em.}; \maintextlang{ṅaran·\ } \textbf{\textsc{A}}.}}, aya ta nu dipikən ku sakalih, kəsit tuṅi diturutan, pituahənana, hantə dek \edtext{mənaṅ}{\lemma{mənaṅ}\variant{\emph{em.}; \maintextlang{mənaṁ minaṁ\ } \textbf{\textsc{A}} (dittography).}}\folio{-Akva2dva[\textbf{A}:10v]mitinəṅkən-} mitinəṅkən maneh, dəṅ hantə dek ñyar na pirampesənana, nihan sinaṅguh pañca-iyatna ṅaranya, 5. }\edlabel{parallel-d1e2450-end}\edtext{}{\linenum{|\xlineref{parallel-d1e2450-start}|||\xlineref{parallel-d1e2450-end}}\parallels{
            Cf. SiGu 3.2: \emph{akrodho, ṅa, tar dadi ika saṅ sevaka dharma, mentonakәna krvadhanya i harəpәn saṅ guru, ṅuniveh i para sujanma kabaih, guruśuśruṣā ṅaranya, bakty anukul ta kita ri saṅ guru, tar madvah ri suku saṅ matuha, tuhu maṅkana yar hana pakvan saṅ guru, pariśuddha ta kunaṅ, kayatnakna ta ṅ trikāya paramārtha, ya ulah rahayu, śabda rahayu, ambәk rahayu, advah parək kayatnakna ikaṅ trikāya maṇḍala pariśuddha mvaṅ daśaśīla, pañcaśikṣā, nihan kaśuśrūṣāniṅ maṅguru ṅaranya, śauca masəhan taṅan, yan gaməlәn taḍahәn saṅ guru, ṅuniveh drabya hyaṅ saṅ paṇḍita, āhāralāghava, śīghra ta kitānaḍah, agәṅ kәpәl kāmakara śīghrānaḍah, hayva ta kita maṅkana, ya kukṣi pura ṅaranya, umapa pva deniṅ manaḍah kaliṅanya, ya ta prāṇa sadhāraṇa juga upajīvaniṅ umaṅən-aṅәn saṅ hyaṅ hayu, nihan pañcaśikṣā, ṅa, kayatnakna saṅ sevaka dharma}.
        }}\pend`

**Comment by aditiagunawan** [comment]
Dear @aso2101 

Here is the generated tex. I copy the whole `<div>`, because I think that you and I have a different result:

\pstart
\label{p:sasanamahaguru_08.01}\maintextlang{nihan sinaṅguh pañca-iyatna ṅaranya, ndah ya nihan silokanya.}\pend


\pstart\label{p:sasanamahaguru_08.02}\maintextlang{\noindent\edlabel{parallel-d1e2419-start}\mbox{\quad\quad\quad}\edtext{akrodho}{\lemma{akrodho}\variant{ \emph{norm.}; \maintextlang{Akva2dva\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} \edtext{guruśuśruṣā, śaucam}{\lemma{guruśuśruṣā, śaucam}\variant{\emph{conj.}; \maintextlang{gurusuci\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} \edtext{āhāralāghavam}{\lemma{āhāralāghavam}\variant{\emph{em.}; \maintextlang{Amaralagavamə·\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}},\\
\mbox{\quad\quad\quad}\edtext{apramādaś ca pañca vaite}{\lemma{apramādaś ca pañca vaite}\variant{\emph{conj.}; \maintextlang{hana pramadasvate\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} \edtext{niyamāḥ parikīrtitāḥ}{\lemma{niyamāḥ parikīrtitāḥ}\variant{\emph{em.}; \maintextlang{nayimaḥ paririkita\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}}, 
}\edlabel{parallel-d1e2419-end}\edtext{}{\linenum{|\xlineref{parallel-d1e2419-start}|||\xlineref{parallel-d1e2419-end}}\parallels{
            Cf. SiGu 3.2: \emph{akrodho, ṅa, tar dadi ika saṅ sevaka dharma, mentonakәna krvadhanya i harəpәn saṅ guru, ṅuniveh i para sujanma kabaih, guruśuśruṣā ṅaranya, bakty anukul ta kita ri saṅ guru, tar madvah ri suku saṅ matuha, tuhu maṅkana yar hana pakvan saṅ guru, pariśuddha ta kunaṅ, kayatnakna ta ṅ trikāya paramārtha, ya ulah rahayu, śabda rahayu, ambәk rahayu, advah parək kayatnakna ikaṅ trikāya maṇḍala pariśuddha mvaṅ daśaśīla, pañcaśikṣā, nihan kaśuśrūṣāniṅ maṅguru ṅaranya, śauca masəhan taṅan, yan gaməlәn taḍahәn saṅ guru, ṅuniveh drabya hyaṅ saṅ paṇḍita, āhāralāghava, śīghra ta kitānaḍah, agәṅ kәpәl kāmakara śīghrānaḍah, hayva ta kita maṅkana, ya kukṣi pura ṅaranya, umapa pva deniṅ manaḍah kaliṅanya, ya ta prāṇa sadhāraṇa juga upajīvaniṅ umaṅən-aṅәn saṅ hyaṅ hayu, nihan pañcaśikṣā, ṅa, kayatnakna saṅ sevaka dharma}.
        }}\pend

\pstart
\label{p:sasanamahaguru_08.03}\maintextlang{ka, \edtext{\textbf{akrodho}}{\lemma{\textbf{akrodho}}\variant{ \emph{norm.}; \maintextlang{Akva2dva\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} ṅaranya, tan dadi ikaṅ saṅ sevaka darma, mitonakən \edtext{krodanya riṅ}{\lemma{krodanya riṅ}\variant{\emph{em.}; \maintextlang{kva2danyaniṁ\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} harəpən saṅ matuha, maṅkaṅuni di nu reya, \edtext{\textbf{āhāralāghavam}}{\lemma{\textbf{āhāralāghavam}}\variant{\emph{em.}; \maintextlang{Aralagavəg·\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} ṅaranya, teka sumari sumarəmbah, hantə ṅənah basa ñatu basa ṅinum, di harəpən saṅ pandita, \edtext{\textbf{apramādaś ca pañca vaite}}{\lemma{\textbf{apramādaś ca pañca vaite}}\variant{\emph{conj.}; \maintextlang{Ahanaprəmadasvate\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}} \edtext{ṅaranya}{\lemma{ṅaranya}\variant{\emph{em.}; \maintextlang{ṅaran·\ }\textbf{\textsc{\textbf{\textsc{A}} }}{.}}}, aya ta nu dipikən ku sakalih, kəsit tuṅi diturutan, pituahənana, hantə dek \edtext{mənaṅ}{\lemma{mənaṅ}\variant{\emph{em.}; \maintextlang{mənaṁ minaṁ\ }\textbf{\textsc{\textbf{\textsc{A}} }} (dittography){.}}}\folio{-Akva2dva[\textbf{A}:10v]mitinəṅkən-} mitinəṅkən maneh, dəṅ hantə dek ñyar na pirampesənana, nihan sinaṅguh pañca-iyatna ṅaranya, 5. }\pend

**Comment by ajaniak** [comment]
Thanks Andrew, I have merged your pull request to make testing easier for Aditia.

**Comment by arlogriffiths** [comment]
@aditiagunawan : are any of the above isses still relevant?

**Comment by aditiagunawan** [comment]
@arlogriffiths  
@ajaniak 
The issue "lac. for larger gap sometimes displayed when not supposed to" above is still found in the pdf file.

**Comment by ajaniak** [comment]
Can you give more precision please?

**Comment by arlogriffiths** [comment]
for some reason this comment does not show up on https://github.com/erc-dharma/tfd-nusantara-philology/issues/100

Le 27 avr. 2023 à 19:21, ajaniak ***@***.******@***.***>> a écrit :



Can you give more precision please?

**Comment by arlogriffiths** [comment]
@aditiagunawan : note that @ajaniak asked you "Can you give more precision please?" please show an example of what is still not going as expected.

**Comment by aditiagunawan** [comment]
@ajaniak 

Please run tei-to-latex sasana, you will see that many cases of _lac._ **B** appear when they should not be, or the other way arround. I suppose this is due to the schema on lacunaStart and lacunaEnd in the xml, while it goes well in html.

Best,
Aditia

**Comment by arlogriffiths** [comment]
@aditiagunawan — I think it may be helfpul for Axelle if you show her the difefrence between html and pdf by attaching two screenshots for the same passage.

**Comment by aditiagunawan** [comment]
@arlogriffiths @ajaniak 

Here is an example. In the HTML version of the Sasana Mahaguru 1.2, the edited word kady aṅganiṅ is correctly displayed in the the apparatus.

<img width="1295" alt="Screenshot 2023-04-28 at 20 10 53" src="https://user-images.githubusercontent.com/55530631/235157171-78e31597-e660-4002-8f97-098142bf2ba2.png">

While in the pdf file, lac. B is missing in the apparatus, and also in the next apparatus. 

<img width="481" alt="Screenshot 2023-04-28 at 20 11 16" src="https://user-images.githubusercontent.com/55530631/235157381-a10a496f-c4d8-4113-882a-be0de8f8bbbe.png">


Best,
Aditia

**Comment by arlogriffiths** [comment]
Thanks Aditia. Let's hope @ajaniak  can quickly solve this, and if not hopefully @aso2101 can quickly intervene.

Please do answer my question about the other two check boxes.

**Comment by aditiagunawan** [comment]
@arlogriffiths I don't really understand what is the meaning of the two check boxes. 

@ajaniak please remind me. 

Best.

**Comment by arlogriffiths** [comment]
"aligning subscript and superscript" meant that it would be nicer if "a.c." and "p.c." could be pushed to the left to stand entered (horizontally) under ASD in cases like you see in this screenshot.

<img width="214" alt="Capture d’écran 2023-05-03 à 18 10 27" src="https://user-images.githubusercontent.com/835603/235889019-8e3b6683-e70c-4dfa-b53f-12aeb6503c0e.png">

@michaelnmmeyer : can you fix this?

I guess that " omission for larger gap need to be added" meant that the XLST must be able to deal with pairs of `<span type="omissionStart">` and `<span type="omissionEnd">` in a manner analogous to cases of `<lacunaStart>` / `<lacunaEnd>`. 

@ajaniak : what is the status on this last point?

**Comment by michaelnmmeyer** [comment]
@arlogriffiths I added a LaTeX macro for doing that in Aditya's PhD repo (commit P171a22fe407c45f15104c7011bb0bf6e35682f0a).

**Comment by arlogriffiths** [comment]
thanks @michaelnmmeyer ! I am not sure if I am seeing the intended effect of your macro in the following screenshot:

<img width="331" alt="Capture d’écran 2023-05-04 à 08 23 55" src="https://user-images.githubusercontent.com/835603/236078740-7385ea63-b003-410b-9cb2-f9cd20484a1a.png">

In any case, this is not what I intended. The labels ASD for the editors of the edition in question have been made invisible. What I was hoping to get was a superposition of that label above the label p.c./a.c. (**which in fact we'd better change to pc/ac without full stops**) somewhat analogously to what we see in the apparatus of the critical edition of the Skandapurāṇa. See the following screenshot:

<img width="547" alt="Capture d’écran 2023-05-04 à 08 28 16" src="https://user-images.githubusercontent.com/835603/236079324-4d905c20-840f-419d-a622-4f0377dca2d6.png">

See e.g. the first witness cited in the first apparatus entry (S2 reads स pc but सं ac). The only difference is that the Skandapurāṇa team puts pc/ac labels above whereas I propose to put them below any extension of a siglum.

I hope it its clear now.

**Comment by michaelnmmeyer** [comment]
@arlogriffiths I defined a new macro, but I've not used it so far in Aditia's thesis. (The initial plan was to modify the XSLT instead of the generated LaTeX, but this isn't an option anymore given the time constraints.)

In the example you chose, you don't see ASD labels because there are actually none in the generated LaTeX code:
```
\textbf{\textsc{ \textbf{\textsc{A}}\textsubscript{\emph{p.c.}}}}
```
Should I assume that all `\textsubscript{\emph{p.c.}}` must appear below an ASD label, and amend the LaTeX code in consequence?

My macro produces text like this:
![image](https://user-images.githubusercontent.com/11620332/236152509-e0919094-9b8e-4e60-9aa4-dc21b8b0e05e.png)
So I think we understand each other on this point.

**Comment by arlogriffiths** [comment]
Dear @michaelnmmeyer ! Sorry for not paying attention when selecting my first screenshot. **No, the indication ac or pc should only be pushed under the label for the editors in case there is such a label. This means, only in cases where the siglum is built up with the prefix Ed.** And in the case of Aditia's thesis, this means only in the case of #EdASD.

The result of your marco is very nice. The only changes I suggest are 
- to remove the full-stops (as in the htmll example) and 
- to print pc or ac in roman, not in italics (as in the htmll example)
Please make the necessary changes to the macro and implement it in Aditia tex file(s).

Can you open a separate issue to remind yourself to modify the XLST ("The initial plan was to modify the XSLT instead of the generated LaTeX, but this isn't an option anymore given the time constraints") once we have a bit of breathing space after Aditia's PhD dissertation has been finalized?

Once that new issue if opened, I think this issue can be closed.
