### ISSUE TITLE
width of box for parallels

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#101]
I suppose we should make the boxes for parallels and translations equally wide.

<img width="1381" alt="Capture d’écran 2022-12-16 à 12 14 01" src="https://user-images.githubusercontent.com/835603/208027470-44c8739c-5836-4386-bb79-aef2863d7129.png">

**Comment by arlogriffiths** [comment]
parce que lesa valeurs de @corresp ne fonctionnent pas, le mieux sera de ne pas les montrer dans le display. comme ça, la référence manuellement saisie par @aditiagunawan ne sera plus redondante.

**Comment by ajaniak** [comment]
La souci vient des différences d'encodage. J'ai aligné celui du fichier qui posait problème. J'ai ajouté une condition d'exclusion pour les fichiers d'Aditia pour le contenu du `@corresp`.

**Comment by arlogriffiths** [comment]
merci. par curiosité, cette condition d'exclusion se formule où (et comment) dans le code?

**Comment by ajaniak** [comment]
Dans le template pour afficher le contenu des parallèles:

```
<xsl:when test="/tei:TEI[not(@xml:id ='skk' or @xml:id ='sasanamahaguru' or @xml:id ='siksaguru')]">
                                    <xsl:value-of select="replace(descendant-or-self::tei:note/@* except @xml:lang, 'txt:', '')"/>
                                    <xsl:text> </xsl:text>
                                </xsl:when>
```
tous les fichiers ne correspondent pas aux id des fichiers d'Aditia appliquent l'ensemble des attributs à l'exception de `@xml:lang`. Les fichiers d'Aditia tombent dans la condition par défaut qui appliquent simplement le contenu du noeud `<note>`.

**Comment by aditiagunawan** [comment]
Dear @ajaniak 

As far as I remember, the `@parallels` in the `<ListApp>` should be placed inside `<p>`, as per EG. Now I see that all parallels in my xml files have been changed into after `<p>`. 

It seems that the remain problem of latex-to-pdf  is due to the parallels. I receive the warning like this: 

<img width="577" alt="Screenshot 2022-12-19 at 21 27 47" src="https://user-images.githubusercontent.com/55530631/208448543-fdf903e8-0bc8-4d2c-a0ee-44d1ad21bd2f.png">

It is quite strange that the problem only occurs in the Siksa Kandang Karesian file, the other two are good. Am I making a mistake somewhere in my XML file of SiksaKandangKaresian?

**Comment by ajaniak** [comment]
No, the rules have been changed so `<listApp>` should be declared as the first following sibling of `<p>` and `<lg>` to harmonize everything. 
I have the issue for all the texts and haven't been able to find the reason yet.

**Comment by aditiagunawan** [comment]
Dear Axelle,

Please allow me to return to this subject. In the pdf compiling file, the parallel does not refer to the correct line numbers in the `<p>`. In the example of SMG (see screen capture), the line number should be 5–16 instead of 2–4 (referring to lg). Also, I note that when a `<div>` does not have `<lg>` and only contains `<p>`, the parallels do not appear in the pdf.

<img width="799" alt="Screenshot 2022-12-30 at 17 59 40" src="https://user-images.githubusercontent.com/55530631/210063651-df8599cf-7786-4f05-b35f-3dfeaa3e159d.png">

Hope you will find a way to solve this problem.

Best,
Aditia

**Comment by arlogriffiths** [comment]
@ajaniak : can you help resolve this issue?

**Comment by ajaniak** [comment]
I am closing this since it is related to the open issue #100 .
