### ISSUE TITLE
encoding a lacuna that stretches until the end of a text

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#107]
@ajaniak — how should Aditia encode the fact that in Siksa Kandang Karesian, the witness A breaks off a few paragraphs before the end of the text, to avoid an empty § as in this screenshot? Should he create an `<app>` at the very end of the text edition for no opther reason than to be able to encode the corresponding `<lacunaEnd>`? Could we perhaps add some attribute to such cases of `<lacunaStart>`? (But are any attributes allowed on this element?)

<img width="444" alt="Capture d’écran 2023-01-13 à 11 16 21" src="https://user-images.githubusercontent.com/835603/212236759-5d68bc14-a220-424d-bbb4-89393745a7e8.png">

**Comment by ajaniak** [comment]
I am not exactly sure... because in theory all <lacunaStart/> shoud end with a <lacunaEnd/>.
If we add a final app such as ```<app><lem wit="#EdASD #B">palipurna.</lem><rdg wit="#A"><lacunaEnd/></rdg></app>```at the end of the closing chapter.
<img width="676" alt="Capture d’écran 2023-01-13 à 10 38 41" src="https://user-images.githubusercontent.com/33328906/212287920-93219ef6-c3e7-4814-8f4c-11e6c6acc8fb.png">

We will resolve the app entry 1061, but it will generate an unsatisfactory entry for this <lacunaEnd/> note.
<img width="1288" alt="Capture d’écran 2023-01-13 à 10 38 33" src="https://user-images.githubusercontent.com/33328906/212287846-a244821b-da75-4eb7-bb38-04277e00d4df.png">

But we could trick this solution adding an attribute `@rend="hide"` on the last app. 
```<app rend="hide><lem wit="#EdASD #B">palipurna.</lem><rdg wit="#A"><lacunaEnd/></rdg></app>```
so that it is not display, but the anchoring for the <lacunaEnd/> in made and so the display expected for the note 1061 still works.
<img width="430" alt="Capture d’écran 2023-01-13 à 10 40 16" src="https://user-images.githubusercontent.com/33328906/212288496-ae3ee0f2-7801-42bb-9742-08a7ff6374ee.png">

I kind of like this solution since it keeps the logic of our model, and we achieve the display without adding anything new nor special. 

I also though of adding a fallback the add an anchor for a `<lacunaStart/>` at the end of the text, but I am afraid it will cause issue and lack the abilty to adapt to different context.

**Comment by arlogriffiths** [comment]
@ajaniak — I entirely agree with your proposal. Can you use the elements of your response to make the necessary additions to EGC to address this kind of scenario?

@aditiagunawan — Please make the necessary changes in your xml file(s) and respond to this comment when you are done. We will wait for Axelle to be done with the EGC before closing this issue.

**Comment by aditiagunawan** [comment]
@ajaniak 

Done!

Thank you
Aditia

**Comment by ajaniak** [comment]
Thnaks @aditiagunawan I have just corrected the double final dot. 
A draft have been added in the encoding guide, so I am closing this
