### ISSUE TITLE
Display: choice of font

### ISSUE THREAD

**Issue by m-schoettel** [erc-dharma/tfd-nusantara-philology#11]
The choice of font for our editions can be discussed here. We have considered using Noto light.

@ajaniak @arlogriffiths  @aditiagunawan

**Comment by ajaniak** [comment]
I will need a little more than that to know what to apply since the Noto family has more than 100 font faces. 

The light style is possible for the following font face with latin alphabeats: 
- Noto sans 
- Noto Sans Display
- Noto Sans Mono
- Noto Serif
- Noto Serif Display

See https://www.google.com/get/noto/

**Comment by aditiagunawan** [comment]
If I may, I prefer Noto Serif. Arlo and I use this font recently for our article and it is nice. It can be read clearly and so far we have no issues of diacritic problems.

**Comment by ajaniak** [comment]
Noto Serif has been added, the server might need a few hours to apply the changes though.

**Comment by arlogriffiths** [comment]
thanks Axelle!
