### ISSUE TITLE
Italic missing in pdf of the translations

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#117]
Dear @ajaniak 

I have made a pull from the repository aditia-phd. There was no problem before, but now there is a problem with italic in the pdf generated from translation files in XML (see screenshot) (From file: DHARMA_CritEdSiksaGuru_transEng01.xml). I encoded as `<foreign>` in the files. 

![Screenshot 2023-02-20 at 16 16 13](https://user-images.githubusercontent.com/55530631/220063761-4818f85d-3321-44c1-a59e-428f66f6593f.jpg)

Do you know what happen? 

Best,
Aditia

**Comment by arlogriffiths** [comment]
Hope you can quickly idnetify the source of this problem, @ajaniak. It might be useful to plan a zoom session with Aditia, because I am not sure of the workflow he has followed to arrive at the current contents of his file DHARMA_CritEdSiksaGuru_transEng01.xml and I guess the source if the problem may lie there.

**Comment by ajaniak** [comment]
No the issue lies in the fact that there is no solution to stabilize xml espaced characters (neither Andrew nor mine)  and in the fact that the footnote for parallels is acting weird again. So for now, i have cleaned the code so italic is restore but expect if you delete all "&amp;" and "&gt;" from your file, you will have issues.

**Comment by arlogriffiths** [comment]
@aditiagunawan — what is the status of this issue?
