### ISSUE TITLE
Blank page and Colophon

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#119]
Dear @aso2101!

I want to add two issues regarding xml to latex transformation:
- There are still a few blank pages in the chapter shift of the edition. Can it be controlled ? To give you a context, please see my screen shot, taken from the Śikṣā Guru edition (pp. 212–125 in pdf). 

- `<div type="chapter" n="14"><ab xml:id="siksaguru_14.01" type="colophon">` in the Śikṣā Guru and `<div type="chapter" n="47" xml:id="smg_47">
<ab xml:id="smg_47.01" type="colophon">`in the Sasana Mahaguru should not generate a new page in LaTex, but be treated as the last `<p>` in the `<div ="chapter">` which it follows

Best,
Aditia

<img width="430" alt="Screenshot 2023-03-03 at 11 44 31" src="https://user-images.githubusercontent.com/55530631/222633619-54c4812e-aa3b-4683-b38b-af14c20c97b9.png">
<img width="412" alt="Screenshot 2023-03-03 at 11 45 07" src="https://user-images.githubusercontent.com/55530631/222633638-30cc1a2d-f7ee-4e0d-8562-50292396652e.png">
<img width="421" alt="Screenshot 2023-03-03 at 11 45 19" src="https://user-images.githubusercontent.com/55530631/222633643-8e13de95-6106-4a9a-b946-5ac9c14cf5ad.png">
<img width="375" alt="Screenshot 2023-03-03 at 11 45 28" src="https://user-images.githubusercontent.com/55530631/222633649-77fe6ddb-9044-4c74-a930-3276ad5bd2e0.png">

**Comment by ajaniak** [comment]
@aditiagunawan 

I have this when I am running the code:

<img width="1196" alt="Capture d’écran 2023-03-03 à 10 25 40" src="https://user-images.githubusercontent.com/33328906/222683224-dc0425b2-0a0d-4e75-b068-5594ffb6ec2b.png">
<img width="1180" alt="Capture d’écran 2023-03-03 à 10 25 51" src="https://user-images.githubusercontent.com/33328906/222683233-0d2be684-9071-4f91-9fc1-6557bf4181ea.png">

Have you pushed all the recent modification of your text so that we can take a look with the same files as you?

Best, 
Axelle

**Comment by aditiagunawan** [comment]
@ajaniak 

I pushed now the necessary files, please regenerate. I make some adjustment manually. I will sent a list of my adjustment in LaTex very soon.

Best,
Aditia

**Comment by arlogriffiths** [comment]
@aditiagunawan : can this issue be closed?
