### ISSUE TITLE
Display errors in PYñ 29.6 to 31

### ISSUE THREAD

**Issue by andreaacri** [erc-dharma/tfd-nusantara-philology#135]
The stanzas do not display correctly in PYñ from canto 29.6 to the end of 31 (lemmata appear  after the stanza in which they occur). I cannot find any errors in the code—the lemmata are the same as in the stanzas, the order of the lines is correct, and the file validates. I'm not sure about what is going on.

**Comment by arlogriffiths** [comment]
@andreaacri — in general, you need to assign issues to a person whom you wish to take care of it, and it is helpful to apply a label. I have applied the label "bug" and assigned this issue to @michaelnmmeyer. It is also helpful of you include links to the relevant XML file and html display, because Michaël may not know what PYñ is and may not like being expected to spend time finding out.

@michaelnmmeyer — I know you are still focused on inscriptions, but I hope you can carve out some time to help solve this specific issue. The edition in question is https://erc-dharma.github.io/tfd-nusantara-philology/output/critical-edition/html/DHARMA_CritEdKakavinParthayajna.html.

**Comment by michaelnmmeyer** [comment]
The `<listApp>` corresponding to these stanzas were missing an attribute `@type="apparatus"`, but the schema did not complain about it. This is fixed now.
