### ISSUE TITLE
encoding gaps in witnesses for critical editions

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#17]
@aditiagunawan —
You have this code in your file SiksaKandangKaresian-CritEd:

`<app><lem type="conj" source="bib:Atja+SalehDanasasmita1981_03">saṅ hyaṅ</lem><rdg wit="A"><gap reason="lost" quantity="1" unit="character"/><seg type="component" subtype="body"><gap reason="lost" quantity="1" unit="component"/></seg>yaṁ</rdg><rdg wit="#B"/></app>`

present display: 

<img width="335" alt="Capture d’écran 2021-03-11 à 17 14 38" src="https://user-images.githubusercontent.com/835603/110818371-7af7ec80-828d-11eb-8ba9-98e35a2ff3c5.png">

I think you mean that the words _saṅ hyaṅ_ are entirely lost due to physical damage in `#B` and partly lost due to physical damage in `#A`. Is that correct? In other words, do we find this in your two diplomatic editions?

- A: `hana ta <gap reason="lost" quantity="1" unit="character"/><seg type="component" subtype="body"><gap reason="lost" quantity="1" unit="component"/></seg>yaṁ siksa kandaṁ`
- B: `hana ta <gap reason="lost" quantity="2" unit="character"/> siksa kandaṁ`

If so, your encoding of the gap in your witness `#B` is certainly incorrect. (Maybe the encoding of the gap in `#A` is also incorrect, but at the moment we don't seem to have given clear guidance on such a case yet in the draft of EGC.) Indeed, you have many other cases of `<rdg wit="#B"/>`, but this encoding should only be used if the scribe has omitted the `<lem>`, not if the absence of `<lem>` in the witness is due to physical damage. 

@ajaniak — I started to try to represent the above scenario using `<lacunaStart/>` and <lacunaEnd/>` but that doesn't seem to work, because we'd have to use them right next to each other

`hana <app>
           <lem type="conj" wit="#EdASD">ta saṅ hyaṅ siksa</lem>
          <rdg wit="#A">ta<lacunaStart/><lacunaEnd/>yaṁ siksa</rdg>
          <rdg wit="#B">ta<lacunaStart/><lacunaEnd/>siksa</rdg>
          </app>
kandaṅ`

Please confirm that that is also incorrect, and please give us a valid suggestion.

By the way, for an empty `<rdg>` due to gap, I suggest we could introduce `<rdg wit="#B" cause="lacuna"/>` to get something like _lac._ instead of _om._ in the display of that witness.

**Comment by aditiagunawan** [comment]
Dear Arlo,

Thank you for your correction. Indeed, I should check all the cases of physical damages in `<wit>`, basically it occurs in the first part of the text. At that time there was no any fix guidelines how to do with lacuna, whether small gap or very big gap due to physical damages. I will check and looking closely the first part of #B. 

Your suggestion `<rdg wit="#B" cause="lacuna">` seems good and useful for me. 

Best,
Aditia

**Comment by ajaniak** [comment]
As a main approach of the lacunae subject - not taking into account specific missing characters for instance:
- I would use `<gap/>` for a text has been lost from the entire tradition, not just in one to several witnesses. 
- If you have only a conjectural lacuna you could still use `<gap/>`but not on its own; withl `@type`, a `<supplied>` or the attribute `@cause` or several of those. 
- `<lacunaStart/>` and `<lacunaEnd/>`are to be used only for gap of text in one of several witnesses, but not to the entire tradition. Their main role is to be used for cross boundaries `<app>` or if the gap runs across several `<app>`. So your example, ` <rdg wit="#B">ta<lacunaStart/><lacunaEnd/>siksa</rdg> ` isn't a proper use of those elements, that's why it seems weird to you! 
```
hana <app> <lem type="conj" wit="#EdASD">ta saṅ hyaṅ siksa</lem> <rdg wit="#A">ta<lacunaStart/>yaṁ siksa</rdg> <rdg wit="#B">ta<lacunaStart/>siksa</rdg> </app> kandaṅ [...] <app><lem/><rdg wit="#A"><lacunaEnd/>blable</rdg> <rdg wit="#B"><lacunaEnd>blable</rdg></app>
```
- regarding  `<rdg wit="#B" cause="lacuna"/>`, I wonder if a structure such as `<app type="lacuna-line"><lem>...</lem><rdg  wit="#B" /></app>` wouldn't be more attune with some other propositions you have made in the guidelines. It means that the <rdg/> could be kept for only omitted textual elements, at least if you decide to have a clear distinction between the 2 phenomenas.

**Comment by arlogriffiths** [comment]
Thanks Axelle. Let us discuss the various options during our next meeting on Tuesday. Till then, Aditia, please wait and don't yet start to revise the encoding of the first part of your text.

**Comment by arlogriffiths** [comment]
@aditiagunawan : I have spoken with Axelle. She and I agree that the example at hand should be encoded as follows:

` <app><lem type="conj" wit="#EdASD">saṅ hyaṅ</lem><rdg wit="A"><gap reason="lost" quantity="1" unit="character"/><seg type="component" subtype="body"><gap reason="lost" quantity="1" unit="component"/></seg>yaṁ</rdg><rdg wit="#B"><gap reason="lost" quantity="2" unit="character"/></rdg></app>`

In other words, you should search all cases where you have encoded only `<rdg wit="..."/>` and where this is not intended to express scribal omission but rather a physical gap in the witness. You should in all those cases encode a `<gap/>` inside the `<rdg>`, as in the example above.

The display will provisionally be: "[...][...] B".

Today, I don't see any need any more to introduce anything like the `<rdg wit="#B" cause="lacuna">` that I was thinking about last week, as it would not work in a case like the above example, where one of the witnesses has a gap that covers only part of the extent of the `<lem>`.

Please close this issue when you have taken note and started making the necessary changes in your file(s).

**Comment by aditiagunawan** [comment]
Dear @arlogriffiths, I have take a note. You can close this issue.
