### ISSUE TITLE
encoding the Svayambhu

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#5]
@aso2101 and @ajaniak : I have just created and pushed this file [https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/Svayambhu-CritEd.xml](https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/Svayambhu-CritEd.xml).

The text in question is structured around subaudible stanzas from a Sanskrit text. Please take a look at my proposals for how to encode the edition and the translation of such a situation, and give feedback. Please also peruse the teiHeader and give feedback on it too.

@ajaniak : I don't see my co-editor Tim Lubin among possible assignees. Please check if he is registered as member of the DHARMA organization and of TF-D. If he isn't yet, please send him an invite.

**Comment by ajaniak** [comment]
I have just invited @lubint in TF-D.

**Comment by arlogriffiths** [comment]
@ajaniak (and @aso2101 ) please take a look at the current version, with two questions marked with "argr2axja" — I look forward to your feedback, and @ajaniak  am coying both relevant strings of code into the draft EGC (at the top of the file) so you can find a place for them and write guidance for such scenarios into the guide..

**Comment by ajaniak** [comment]
I am rather reluctant about this empty `<p>` and I wouldn't recommended it, since it is not exactly TEI conformant. If you can't identify a base text, then not having one in your section should be enough to say so. Eventually adding a `<note>` to make sure the situation is clear enough for the reader. 

I guess you could add a `<lacunaStart/>` and a `<lacunaEnd/>` to avoid the repetition of the empty `<rdg wit="#K"/>`, but I tend to use it when it covers more apparatus entries than one or two. In the present situation, you could express the ` <rdg wit="#K"/>` once and not twice (in fact, we have one apparatus entry fragmented because an overlapping structure). The second doesn't provide new information in this context, so Indeed you could delete it!
