### ISSUE TITLE
encoding questions

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#6]
1. `<ab type="invocation" xml:lang="san-Latn"><pb ed="#L" n="1"/><pb ed="#K" n="1v"/>//0// avighnam astu //0//</ab>`
`<!-- argr: do we need a div around this ab? in Marine's Rsisasana, she has it -->`

**Comment by ajaniak** [comment]
If I remember correctly  we needed a `<div>` to structure the trailing `<ab>` at the end of her edition. Since the stucture was based on `<div>` elements the parser could comprehend the sudden change of element and marked it as wrong. So we added a `<div>`to validate it and to keep it independent form the previous `<div>` element. For constancy sake, we also added one for the heading element `<ab>`.
