### ISSUE TITLE
Unwanted apparatus

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#70]
Dear @ajaniak 

I found unwanted apparatus numbers in HTML transformation of Siksa Guru (see screenshot). This seems to be related to the translation file linked to the Critical Edition where I added `<note>` to the translation (please check my translation file). Do you know how to solve the problem?

<img width="1436" alt="Screenshot 2022-06-15 at 09 29 32" src="https://user-images.githubusercontent.com/55530631/173723951-1e86575e-d5bb-422c-890a-5db9cb71106a.png">

Thanks!

**Comment by arlogriffiths** [comment]
I suggest the following to accommodate the presence of `<note>` in translations, if it's technically possible:

1. for the "traditionional" display of apparatus at the bottomw of the edition, we already have a heading "Apparatus". Now below that, let us have a heading "Translation Notes" and arrange the contents of the notes there.
2. let us display numbered _appels de note_ in the translation boxes in the same manner as the current display of `<note>` in the epigraphic editions.

What do you think, Axelle?

**Comment by ajaniak** [comment]
I have added it in the codes

<img width="1342" alt="Capture d’écran 2022-06-15 à 13 01 44" src="https://user-images.githubusercontent.com/33328906/173812113-80704fe4-6c08-4912-bc1f-74c2d40ff633.png">

I added the notes in the bottom of the window of each translation as well, since I wasn't sure to which extent you wanted the epigraphic editions display. I like it but I can delete it if necessary. 
<img width="836" alt="Capture d’écran 2022-06-15 à 13 01 32" src="https://user-images.githubusercontent.com/33328906/173812322-381210c7-97a9-4462-a136-41e8b2f1fbbd.png">

Regarding the coloring, do you have specifics?

**Comment by aditiagunawan** [comment]
It seems that the text of the footnote still occurs in the body text.

**Comment by ajaniak** [comment]
I don't see anything in the body text, have you actualized your page and its version?

**Comment by aditiagunawan** [comment]
Yes, I have this in my version:
<img width="836" alt="173812322-381210c7-97a9-4462-a136-41e8b2f1fbbd" src="https://user-images.githubusercontent.com/55530631/173817861-579de326-89ff-4685-afeb-996320d86c63.png">

You see that the text of footnote no.1 still occurs in the body text of translation.

**Comment by ajaniak** [comment]
You are on the latest version online but not on the latest version

<img width="890" alt="Capture d’écran 2022-06-15 à 13 47 15" src="https://user-images.githubusercontent.com/33328906/173820071-5865fa80-147d-4959-ac52-37e423e6ac7d.png">

**Comment by arlogriffiths** [comment]
Thanks a lot Axelle. I think we need only one representation of the Translation Note, but at the moment I find it hard to decide which one to keep. Since the clicking back and forth between up/down arrows only works between the translations and the section Translation Notes at the bottom of the file, keeping only the latter may eventually be the best choice. Let's decide later and keep this thread open as reminder.

**Comment by ajaniak** [comment]
I have added the link from the number with the section Translation, but from the notes to the text it works from both, unless the window translation isn't open and in that case the link doesn't work from the section.
