### ISSUE TITLE
Encoding bibliography on TEI Header

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#76]
Dear @ajaniak 

The element `<bibl>` on the header does not appear ini the HTML (see HTML and the encoding captured below). Could you make it works in the transformation or maybe this is not allowed? 

<img width="507" alt="Screenshot 2022-06-25 at 12 19 59" src="https://user-images.githubusercontent.com/55530631/175759657-ef4fe2c0-40ef-41a1-8a18-7dbe7c0cd033.png">

<img width="1275" alt="Screenshot 2022-06-25 at 12 23 23" src="https://user-images.githubusercontent.com/55530631/175759660-96403385-b638-48aa-9109-3d529a3d997f.png">

Thanks!

**Comment by arlogriffiths** [comment]
Thanks Axelle! Can you give any recommendations on how to reduce variety and hence increase your ability to control display?

@aditiagunawan : It would be nicer to avoid (...) within (...) and to rewrite your xml code so that you get this in html: "The manuscript is from Cilegon, Tarogong District, Garut, as reported in ROD (1914): № 208, 71–72." Anyhow, I am pretty sure RID is just repeating information from an earlier publication, and you should try to recover the scholarly history and cite the earliest relevant publication. Close this issue when you're done.

**Comment by arlogriffiths** [comment]
@aditiagunawan 
Are you done?

**Comment by aditiagunawan** [comment]
@arlogriffiths done with the encoding, but I need to check the earlier publication referred by ROD.
