### ISSUE TITLE
Pipeline manuscripts workflow

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#90]
Dear @ajaniak 

I find that there is still an issue of pipeline. I can't push my work until now. Can you fix it?

Thank you,
Aditia

**Comment by arlogriffiths** [comment]
dear Aditia: we do see a recent commit of yours on github, so the problem does not seem to be whether you are able to push or not. I think you are confusing the possibility top push and the success of the workflow generating new html displays.

screenshot

<img width="1225" alt="Capture d’écran 2022-10-18 à 14 19 06" src="https://user-images.githubusercontent.com/835603/196363091-171864df-c7c4-427b-a711-1baba366707a.png">

by the way, why are your commits linked to such a strange username "your_username" and not to "aditiagunawan". if you don't know yourself, maybe you should discuss the fact with Axelle.

**Comment by ajaniak** [comment]
Dear @aditiagunawan, 

It is fixed, I was migrating version inside the script. 
But, as have underline Arlo, pushing and the pipeline running are two different things. The issue was your push couldn't be used to run a new display and not on the pushing itself. 

To change "your_username", open your terminal:
`git config --global user.name "aditiagunawan"`

then, confirm that you have set the Git username correctly
`git config --global user.name`
it should tell you 
`> aditiagunawan`

Best,
